### ISSUE TITLE
Drag Drop is getting stuck

### ISSUE THREAD

**Issue by dolly-chhabriya-altius** [BasicPrimitives/react-demo#54]
Hello team,

While doing drag and drop for a particular node sometimes it gets stuck and does not move the node.

**Comment by BasicPrimitives** [comment]
1. Try to clone our repo and run our demo org editor locally in isolation without dynamically loaded samples.
2. Our component does not implement any built in support for Drag & Drop, the entire Drag & Drop functionality is implemented with custom templates and global Drag & Drop context provided by 3d party library. The point is that the bug is not in our library, but in our samples and demo code.
