### ISSUE TITLE
How to find out children and and all the grand children of a node.

### ISSUE THREAD

**Issue by anchal-chouvhan-altius** [BasicPrimitives/react-demo#57]
I have a parent node in the tree. I want to find out all the children and grand children of that node. There could be n number of levels below that parent node. Can you please let us know if there is a way to do this in basic primitives.There is property called parent but with that I can only find the immediate children not all the grandchildren.

**Comment by BasicPrimitives** [comment]
We use Tree structure internally, we document its API at our web site, just because we use it ourselves for our site and other purposes: https://www.basicprimitives.com/reference/algorithms#Tree
Sources: https://github.com/BasicPrimitives/javascript/blob/master/src/algorithms/Tree.js
Tests: https://github.com/BasicPrimitives/javascript/blob/master/src/algorithms/Tree.test.js

See Tests for more details. It has method `loopLevels`, it traverse tree nodes level by level, use  levelid property of the callback function to break tree traversing at required level depth.
```
test('Function loopLevels should break loop on BREAK.', () => {
    const tree = getTree(items);
    const rootItems = [];
    tree.loopLevels(this, function (nodeid, node, levelid) {
        if (levelid > 0) {
            return tree.BREAK;
        }
        rootItems.push(nodeid);
    });
    expect(rootItems).toEqual([0]);
});
 ```
